In [1]:
#utilities
import pandas as pd
import numpy as np

#plotting
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#model building
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [2]:
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [3]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [4]:
matches.shape,deliveries.shape

((1095, 20), (260920, 17))

In [5]:
matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [6]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [7]:
len(matches)

1095

In [8]:
len(deliveries)

260920

In [9]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [10]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [11]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [12]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [13]:
#creating a list of columns and removing unnecessary columns from the list
list1 = matches.columns.to_list()
remove_from_list = ['id', 'date', 'toss_winner', 'toss_decision', 'winner', 
                    'win_by_runs', 'player_of_match', 'venue',
                    'umpire1', 'umpire2', 'umpire3']

In [14]:
for i in list1:
    print('The unique values in', i, 'are: ', matches[i].unique())

The unique values in id are:  [ 335982  335983  335984 ... 1426310 1426311 1426312]
The unique values in season are:  ['2007/08' '2009' '2009/10' '2011' '2012' '2013' '2014' '2015' '2016'
 '2017' '2018' '2019' '2020/21' '2021' '2022' '2023' '2024']
The unique values in city are:  ['Bangalore' 'Chandigarh' 'Delhi' 'Mumbai' 'Kolkata' 'Jaipur' 'Hyderabad'
 'Chennai' 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur'
 'Dharamsala' 'Kochi' 'Indore' 'Visakhapatnam' 'Pune' 'Raipur' 'Ranchi'
 'Abu Dhabi' nan 'Rajkot' 'Kanpur' 'Bengaluru' 'Dubai' 'Sharjah'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Mohali']
The unique values in date are:  ['2008-04-18' '2008-04-19' '2008-04-20' '2008-04-21' '2008-04-22'
 '2008-04-23' '2008-04-24' '2008-04-25' '2008-04-26' '2008-04-27'
 '2008-04-28' '2008-04-29' '2008-04-30' '2008-05-01' '2008-05-02'
 '2008-05-03' '2008-05-04' '2008-05-05' '2008-05-06' '2008-05-07'
 '2008-05-08' '2008-05-09' '2008-05-10' '2008-05-11' '2008-05-12'
 '2008-05-13' '2008-05-14' '2008-05-15' '2008-05-16' '2008-05-17'
 '2008-05-18' '2008-05-19' '2008-05-20' '2008-05-21' '2008-05-23'
 '2008-05-24' '2008-05-25' '2008-05-26' '2008-05-27' '2008-05-28'
 '2008-05-30' '2008-05-31' '2008-06-01' '2009-04-18' '2009-04-19'
 '2009-04-20' '2009-04-21' '2009-04-22' '2009-04-23' '2009-04-24'
 '2009-04-25' '2009-04-26' '2009-04-27' '2009-04-28' '2009-04-29'
 '2009-04-30' '2009-05-01' '2009-05-02' '2009-05-03' '2009-05-04'
 '2009-05-05' '2009-05-06' '2009-05-07' '2009-05-08' '2009-05-09'
 '2009-05-10' '2009-05-11' '2009-05-12' '2009-05-13' '2009-05-14'
 '2009-05-15' '2009-05-16' '2009-05-17' '2009-05-18' '2009-05-19'
 '2009-05-20' '2009-05-21' '2009-05-22' '2009-05-23' '2009-05-24'
 '2010-03-12' '2010-03-13' '2010-03-14' '2010-03-15' '2010-03-16'
 '2010-03-17' '2010-03-18' '2010-03-19' '2010-03-20' '2010-03-21'
 '2010-03-22' '2010-03-23' '2010-03-24' '2010-03-25' '2010-03-26'
 '2010-03-27' '2010-03-28' '2010-03-29' '2010-03-30' '2010-03-31'
 '2010-04-01' '2010-04-02' '2010-04-03' '2010-04-04' '2010-04-05'
 '2010-04-06' '2010-04-07' '2010-04-08' '2010-04-09' '2010-04-10'
 '2010-04-11' '2010-04-12' '2010-04-13' '2010-04-14' '2010-04-15'
 '2010-04-16' '2010-04-17' '2010-04-18' '2010-04-19' '2010-04-21'
 '2010-04-22' '2010-04-24' '2010-04-25' '2011-04-08' '2011-04-09'
 '2011-04-10' '2011-04-11' '2011-04-12' '2011-04-13' '2011-04-14'
 '2011-04-15' '2011-04-16' '2011-04-17' '2011-04-18' '2011-04-19'
 '2011-04-20' '2011-04-21' '2011-04-22' '2011-04-23' '2011-04-24'
 '2011-04-25' '2011-04-26' '2011-04-27' '2011-04-28' '2011-04-29'
 '2011-04-30' '2011-05-01' '2011-05-02' '2011-05-03' '2011-05-04'
 '2011-05-05' '2011-05-06' '2011-05-07' '2011-05-08' '2011-05-09'
 '2011-05-10' '2011-05-11' '2011-05-12' '2011-05-13' '2011-05-14'
 '2011-05-15' '2011-05-16' '2011-05-17' '2011-05-18' '2011-05-19'
 '2011-05-20' '2011-05-21' '2011-05-22' '2011-05-24' '2011-05-25'
 '2011-05-27' '2011-05-28' '2012-04-04' '2012-04-05' '2012-04-06'
 '2012-04-07' '2012-04-08' '2012-04-09' '2012-04-10' '2012-04-11'
 '2012-04-12' '2012-04-13' '2012-04-14' '2012-04-15' '2012-04-16'
 '2012-04-17' '2012-04-18' '2012-04-19' '2012-04-20' '2012-04-21'
 '2012-04-22' '2012-04-23' '2012-04-24' '2012-04-25' '2012-04-26'
 '2012-04-27' '2012-04-28' '2012-04-29' '2012-04-30' '2012-05-01'
 '2012-05-02' '2012-05-03' '2012-05-04' '2012-05-05' '2012-05-06'
 '2012-05-07' '2012-05-08' '2012-05-09' '2012-05-10' '2012-05-11'
 '2012-05-12' '2012-05-13' '2012-05-14' '2012-05-15' '2012-05-16'
 '2012-05-17' '2012-05-18' '2012-05-19' '2012-05-20' '2012-05-22'
 '2012-05-23' '2012-05-25' '2012-05-27' '2013-04-03' '2013-04-04'
 '2013-04-05' '2013-04-06' '2013-04-07' '2013-04-08' '2013-04-09'
 '2013-04-10' '2013-04-11' '2013-04-12' '2013-04-13' '2013-04-14'
 '2013-04-15' '2013-04-16' '2013-04-17' '2013-04-18' '2013-04-19'
 '2013-04-20' '2013-04-21' '2013-04-22' '2013-04-23' '2013-04-24'
 '2013-04-25' '2013-04-26' '2013-04-27' '2013-04-28' '2013-04-29'
 '2013-04-30' '2013-05-01' '2013-05-02' '2013-05-03' '2013-05-04'
 '2013-05-05' '2013-05-06' '2013-05-07' '2013-05-08' '2013-05-09'
 '2013-05-10' '2013-05-11' '2013-05-12' '2013-05-13' '2013-05-14'
 '2013-05-15' '2013-05-16' '2013-05-17' '2013-05-18' '2013-05-19'
 '2013-05-21' '2013-05-22' '2013-05-24' '2013-05-26' '2014-04-16'
 '2014-04-17' '2014-04-18' '2014-04-19' '2014-04-20' '2014-04-21'
 '2014-04-22' '2014-04-23' '2014-04-24' '2014-04-25' '2014-04-26'
 '2014-04-27' '2014-04-28' '2014-04-29' '2014-04-30' '2014-05-02'
 '2014-05-03' '2014-05-04' '2014-05-05' '2014-05-06' '2014-05-07'
 '2014-05-08' '2014-05-09' '2014-05-10' '2014-05-11' '2014-05-12'
 '2014-05-13' '2014-05-14' '2014-05-15' '2014-05-18' '2014-05-19'
 '2014-05-20' '2014-05-21' '2014-05-22' '2014-05-23' '2014-05-24'
 '2014-05-25' '2014-05-27' '2014-05-28' '2014-05-30' '2014-06-01'
 '2015-04-08' '2015-04-09' '2015-04-10' '2015-04-11' '2015-04-12'
 '2015-04-13' '2015-04-14' '2015-04-15' '2015-04-16' '2015-04-17'
 '2015-04-18' '2015-04-19' '2015-04-20' '2015-04-21' '2015-04-22'
 '2015-04-23' '2015-04-24' '2015-04-25' '2015-04-26' '2015-04-27'
 '2015-04-28' '2015-04-29' '2015-04-30' '2015-05-01' '2015-05-02'
 '2015-05-03' '2015-05-04' '2015-05-05' '2015-05-06' '2015-05-07'
 '2015-05-08' '2015-05-09' '2015-05-10' '2015-05-11' '2015-05-12'
 '2015-05-13' '2015-05-14' '2015-05-15' '2015-05-16' '2015-05-17'
 '2015-05-19' '2015-05-20' '2015-05-22' '2015-05-24' '2016-04-09'
 '2016-04-10' '2016-04-11' '2016-04-12' '2016-04-13' '2016-04-14'
 '2016-04-15' '2016-04-16' '2016-04-17' '2016-04-18' '2016-04-19'
 '2016-04-20' '2016-04-21' '2016-04-22' '2016-04-23' '2016-04-24'
 '2016-04-25' '2016-04-26' '2016-04-27' '2016-04-28' '2016-04-29'
 '2016-04-30' '2016-05-01' '2016-05-02' '2016-05-03' '2016-05-04'
 '2016-05-05' '2016-05-06' '2016-05-07' '2016-05-08' '2016-05-09'
 '2016-05-10' '2016-05-11' '2016-05-12' '2016-05-13' '2016-05-14'
 '2016-05-15' '2016-05-16' '2016-05-17' '2016-05-18' '2016-05-19'
 '2016-05-20' '2016-05-21' '2016-05-22' '2016-05-24' '2016-05-25'
 '2016-05-27' '2016-05-29' '2017-04-05' '2017-04-06' '2017-04-07'
 '2017-04-08' '2017-04-09' '2017-04-10' '2017-04-11' '2017-04-12'
 '2017-04-13' '2017-04-14' '2017-04-15' '2017-04-16' '2017-04-17'
 '2017-04-18' '2017-04-19' '2017-04-20' '2017-04-21' '2017-04-22'
 '2017-04-23' '2017-04-24' '2017-04-26' '2017-04-27' '2017-04-28'
 '2017-04-29' '2017-04-30' '2017-05-01' '2017-05-02' '2017-05-03'
 '2017-05-04' '2017-05-05' '2017-05-06' '2017-05-07' '2017-05-08'
 '2017-05-09' '2017-05-10' '2017-05-11' '2017-05-12' '2017-05-13'
 '2017-05-14' '2017-05-16' '2017-05-17' '2017-05-19' '2017-05-21'
 '2018-04-07' '2018-04-08' '2018-04-09' '2018-04-10' '2018-04-11'
 '2018-04-12' '2018-04-13' '2018-04-14' '2018-04-15' '2018-04-16'
 '2018-04-17' '2018-04-18' '2018-04-19' '2018-04-20' '2018-04-21'
 '2018-04-22' '2018-04-23' '2018-04-24' '2018-04-25' '2018-04-26'
 '2018-04-27' '2018-04-28' '2018-04-29' '2018-04-30' '2018-05-01'
 '2018-05-02' '2018-05-03' '2018-05-04' '2018-05-05' '2018-05-06'
 '2018-05-07' '2018-05-08' '2018-05-09' '2018-05-10' '2018-05-11'
 '2018-05-12' '2018-05-13' '2018-05-14' '2018-05-15' '2018-05-16'
 '2018-05-17' '2018-05-18' '2018-05-19' '2018-05-20' '2018-05-22'
 '2018-05-23' '2018-05-25' '2018-05-27' '2019-03-23' '2019-03-24'
 '2019-03-25' '2019-03-26' '2019-03-27' '2019-03-28' '2019-03-29'
 '2019-03-30' '2019-03-31' '2019-04-01' '2019-04-02' '2019-04-03'
 '2019-04-04' '2019-04-05' '2019-04-06' '2019-04-07' '2019-04-08'
 '2019-04-09' '2019-04-10' '2019-04-11' '2019-04-12' '2019-04-13'
 '2019-04-14' '2019-04-15' '2019-04-16' '2019-04-17' '2019-04-18'
 '2019-04-19' '2019-04-20' '2019-04-21' '2019-04-22' '2019-04-23'
 '2019-04-24' '2019-04-25' '2019-04-26' '2019-04-27' '2019-04-28'
 '2019-04-29' '2019-04-30' '2019-05-01' '2019-05-02' '2019-05-03'
 '2019-05-04' '2019-05-05' '2019-05-07' '2019-05-08' '2019-05-10'
 '2019-05-12' '2020-09-19' '2020-09-20' '2020-09-21' '2020-09-22'
 '2020-09-23' '2020-09-24' '2020-09-25' '2020-09-26' '2020-09-27'
 '2020-09-28' '2020-09-29' '2020-09-30' '2020-10-01' '2020-10-02'
 '2020-10-03' '2020-10-04' '2020-10-05' '2020-10-06' '2020-10-07'
 '2020-10-08' '2020-10-09' '2020-10-10' '2020-10-11' '2020-10-12'
 '2020-10-13' '2020-10-14' '2020-10-15' '2020-10-16' '2020-10-17'
 '2020-10-18' '2020-10-19' '2020-10-20' '2020-10-21' '2020-10-22'
 '2020-10-23' '2020-10-24' '2020-10-25' '2020-10-26' '2020-10-27'
 '2020-10-28' '2020-10-29' '2020-10-30' '2020-10-31' '2020-11-01'
 '2020-11-02' '2020-11-03' '2020-11-05' '2020-11-06' '2020-11-08'
 '2020-11-10' '2021-04-09' '2021-04-10' '2021-04-11' '2021-04-12'
 '2021-04-13' '2021-04-14' '2021-04-15' '2021-04-16' '2021-04-17'
 '2021-04-18' '2021-04-19' '2021-04-20' '2021-04-21' '2021-04-22'
 '2021-04-23' '2021-04-24' '2021-04-25' '2021-04-26' '2021-04-27'
 '2021-04-28' '2021-04-29' '2021-04-30' '2021-05-01' '2021-05-02'
 '2021-09-19' '2021-09-20' '2021-09-21' '2021-09-22' '2021-09-23'
 '2021-09-24' '2021-09-25' '2021-09-26' '2021-09-27' '2021-09-28'
 '2021-09-29' '2021-09-30' '2021-10-01' '2021-10-02' '2021-10-03'
 '2021-10-04' '2021-10-05' '2021-10-06' '2021-10-07' '2021-10-08'
 '2021-10-10' '2021-10-11' '2021-10-13' '2021-10-15' '2022-03-26'
 '2022-03-27' '2022-03-28' '2022-03-29' '2022-03-30' '2022-03-31'
 '2022-04-01' '2022-04-02' '2022-04-03' '2022-04-04' '2022-04-05'
 '2022-04-06' '2022-04-07' '2022-04-08' '2022-04-09' '2022-04-10'
 '2022-04-11' '2022-04-12' '2022-04-13' '2022-04-14' '2022-04-15'
 '2022-04-16' '2022-04-17' '2022-04-18' '2022-04-19' '2022-04-20'
 '2022-04-21' '2022-04-22' '2022-04-23' '2022-04-24' '2022-04-25'
 '2022-04-26' '2022-04-27' '2022-04-28' '2022-04-29' '2022-04-30'
 '2022-05-01' '2022-05-02' '2022-05-03' '2022-05-04' '2022-05-05'
 '2022-05-06' '2022-05-07' '2022-05-08' '2022-05-09' '2022-05-10'
 '2022-05-11' '2022-05-12' '2022-05-13' '2022-05-14' '2022-05-15'
 '2022-05-16' '2022-05-17' '2022-05-18' '2022-05-19' '2022-05-20'
 '2022-05-21' '2022-05-22' '2022-05-24' '2022-05-25' '2022-05-27'
 '2022-05-29' '2023-03-31' '2023-04-01' '2023-04-02' '2023-04-03'
 '2023-04-04' '2023-04-05' '2023-04-06' '2023-04-07' '2023-04-08'
 '2023-04-09' '2023-04-10' '2023-04-11' '2023-04-12' '2023-04-13'
 '2023-04-14' '2023-04-15' '2023-04-16' '2023-04-17' '2023-04-18'
 '2023-04-19' '2023-04-20' '2023-04-21' '2023-04-22' '2023-04-23'
 '2023-04-24' '2023-04-25' '2023-04-26' '2023-04-27' '2023-04-28'
 '2023-04-29' '2023-04-30' '2023-05-01' '2023-05-02' '2023-05-03'
 '2023-05-04' '2023-05-05' '2023-05-06' '2023-05-07' '2023-05-08'
 '2023-05-09' '2023-05-10' '2023-05-11' '2023-05-12' '2023-05-13'
 '2023-05-14' '2023-05-15' '2023-05-16' '2023-05-17' '2023-05-18'
 '2023-05-19' '2023-05-20' '2023-05-21' '2023-05-23' '2023-05-24'
 '2023-05-26' '2023-05-29' '2024-03-22' '2024-03-23' '2024-03-24'
 '2024-03-25' '2024-03-26' '2024-03-27' '2024-03-28' '2024-03-29'
 '2024-03-30' '2024-03-31' '2024-04-01' '2024-04-02' '2024-04-03'
 '2024-04-04' '2024-04-05' '2024-04-06' '2024-04-07' '2024-04-08'
 '2024-04-09' '2024-04-10' '2024-04-11' '2024-04-12' '2024-04-13'
 '2024-04-14' '2024-04-15' '2024-04-16' '2024-04-17' '2024-04-18'
 '2024-04-19' '2024-04-20' '2024-04-21' '2024-04-22' '2024-04-23'
 '2024-04-24' '2024-04-25' '2024-04-26' '2024-04-27' '2024-04-28'
 '2024-04-29' '2024-04-30' '2024-05-01' '2024-05-02' '2024-05-03'
 '2024-05-04' '2024-05-05' '2024-05-06' '2024-05-07' '2024-05-08'
 '2024-05-09' '2024-05-10' '2024-05-11' '2024-05-12' '2024-05-14'
 '2024-05-15' '2024-05-17' '2024-05-18' '2024-05-19' '2024-05-21'
 '2024-05-22' '2024-05-24' '2024-05-26']
The unique values in match_type are:  ['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'
 'Elimination Final' 'Qualifier 2' 'Eliminator']
The unique values in player_of_match are:  ['BB McCullum' 'MEK Hussey' 'MF Maharoof' 'MV Boucher' 'DJ Hussey'
 'SR Watson' 'V Sehwag' 'ML Hayden' 'YK Pathan' 'KC Sangakkara' 'JDP Oram'
 'AC Gilchrist' 'SM Katich' 'MS Dhoni' 'ST Jayasuriya' 'GD McGrath'
 'SE Marsh' 'SA Asnodkar' 'IK Pathan' 'P Kumar' 'SM Pollock'
 'Sohail Tanvir' 'S Sreesanth' 'A Nehra' 'SC Ganguly' 'L Balaji'
 'Shoaib Akhtar' 'A Mishra' 'DPMD Jayawardene' 'GC Smith' 'DJ Bravo'
 'M Ntini' 'SP Goswami' 'A Kumble' 'KD Karthik' 'JA Morkel'
 'R Vinay Kumar' 'Umar Gul' 'SK Raina' 'CRD Fernando' 'SR Tendulkar'
 'R Dravid' 'DL Vettori' 'RP Singh' 'M Muralitharan' 'CH Gayle'
 'AB de Villiers' 'RS Bopara' 'PP Ojha' 'TM Dilshan' 'HH Gibbs'
 'DP Nannes' 'JP Duminy' 'Yuvraj Singh' 'SB Jakati' 'JH Kallis'
 'G Gambhir' 'RG Sharma' 'A Singh' 'S Badrinath' 'DR Smith' 'LRPL Taylor'
 'Harbhajan Singh' 'R Bhatia' 'SK Warne' 'B Lee' 'BJ Hodge' 'LR Shukla'
 'MK Pandey' 'AD Mathews' 'MK Tiwary' 'WPUJC Vaas' 'A Symonds'
 'AA Jhunjhunwala' 'J Theron' 'RV Uthappa' 'AC Voges' 'KM Jadhav'
 'NV Ojha' 'DA Warner' 'SL Malinga' 'M Vijay' 'KP Pietersen' 'AT Rayudu'
 'PD Collingwood' 'MJ Lumb' 'TL Suman' 'RJ Harris' 'PP Chawla'
 'Harmeet Singh' 'KA Pollard' 'R Ashwin' 'R McLaren' 'JD Unadkat'
 'M Kartik' 'DE Bollinger' 'S Anirudha' 'SK Trivedi' 'SB Wagh'
 'PC Valthaty' 'MD Mishra' 'DW Steyn' 'S Sohal' 'MM Patel' 'V Kohli'
 'I Sharma' 'J Botha' 'Iqbal Abdulla' 'P Parameswaran' 'R Sharma'
 'MR Marsh' 'BA Bhatt' 'S Aravind' 'WP Saha' 'S Dhawan' nan 'JEC Franklin'
 'RE Levi' 'SPD Smith' 'AM Rahane' 'RA Jadeja' 'MN Samuels' 'M Morkel'
 'F du Plessis' 'AD Mascarenhas' 'Shakib Al Hasan' 'JD Ryder' 'SP Narine'
 'S Nadeem' 'KMDN Kulasekara' 'CL White' 'Mandeep Singh' 'P Negi'
 'Azhar Mahmood' 'BW Hilfenhaus' 'A Chandila' 'UT Yadav' 'MS Bisla'
 'M Vohra' 'GH Vihari' 'AJ Finch' 'JP Faulkner' 'MS Gony' 'DA Miller'
 'SV Samson' 'DJG Sammy' 'MG Johnson' 'KK Cooper' 'PA Patel' 'AP Tare'
 'LJ Wright' 'YS Chahal' 'GJ Maxwell' 'CA Lynn' 'MM Sharma' 'PV Tambe'
 'Sandeep Sharma' 'B Kumar' 'CJ Anderson' 'KK Nair' 'AR Patel'
 'LMP Simmons' 'DJ Hooda' 'GJ Bailey' 'MA Agarwal' 'AD Russell' 'SS Iyer'
 'MA Starc' 'VR Aaron' 'TA Boult' 'NM Coulter-Nile' 'EJG Morgan'
 'HH Pandya' 'MC Henriques' 'Z Khan' 'MJ McClenaghan' 'Q de Kock'
 'Mustafizur Rahman' 'SA Yadav' 'AB Dinda' 'CH Morris' 'CR Brathwaite'
 'RR Pant' 'MP Stoinis' 'A Zampa' 'KH Pandya' 'HM Amla' 'BCJ Cutting'
 'Rashid Khan' 'N Rana' 'JJ Bumrah' 'AJ Tye' 'BA Stokes' 'KS Williamson'
 'JC Buttler' 'LH Ferguson' 'Mohammed Shami' 'RA Tripathi'
 'Mohammed Siraj' 'HV Patel' 'Washington Sundar' 'KV Sharma' 'KL Rahul'
 'SW Billings' 'JJ Roy' 'B Stanlake' 'JC Archer' 'AS Rajpoot' 'TG Southee'
 'Mujeeb Ur Rahman' 'Ishan Kishan' 'Kuldeep Yadav' 'S Gopal' 'L Ngidi'
 'PP Shaw' 'JM Bairstow' 'SM Curran' 'AS Joseph' 'K Rabada' 'HF Gurney'
 'DL Chahar' 'Imran Tahir' 'KMA Paul' 'KK Ahmed' 'Shubman Gill'
 'SO Hetmyer' 'Shivam Mavi' 'PK Garg' 'R Tewatia' 'A Nortje' 'CV Varun'
 'CJ Jordan' 'RD Gaikwad' 'PJ Cummins' 'RD Chahar' 'MM Ali' 'D Padikkal'
 'Harpreet Brar' 'Kartik Tyagi' 'JO Holder' 'JR Hazlewood' 'KS Bharat'
 'VR Iyer' 'OF Smith' 'PWH de Silva' 'E Lewis' 'LS Livingstone'
 'Avesh Khan' 'Abhishek Sharma' 'Anuj Rawat' 'S Dube' 'Umran Malik'
 'Mukesh Choudhary' 'M Jansen' 'R Parag' 'Mohsin Khan' 'RK Singh'
 'TH David' 'YBK Jaiswal' 'DP Conway' 'DR Sams' 'SN Thakur' 'RM Patidar'
 'Arshdeep Singh' 'MA Wood' 'B Sai Sudharsan' 'NT Ellis' 'N Pooran'
 'HC Brook' 'Sikandar Raza' 'C Green' 'A Manohar' 'J Little' 'M Pathirana'
 'PD Salt' 'GD Phillips' 'PN Mankad' 'P Simran Singh' 'WD Parnell'
 'RR Rossouw' 'Akash Madhwal' 'MP Yadav' 'Shashank Singh' 'R Shepherd'
 'Yash Thakur' 'Nithish Kumar Reddy' 'TM Head' 'R Sai Kishore'
 'J Fraser-McGurk' 'WG Jacks' 'Simarjeet Singh' 'Shahbaz Ahmed']
The unique values in venue are:  ['M Chinnaswamy Stadium' 'Punjab Cricket Association Stadium, Mohali'
 'Feroz Shah Kotla' 'Wankhede Stadium' 'Eden Gardens'
 'Sawai Mansingh Stadium' 'Rajiv Gandhi International Stadium, Uppal'
 'MA Chidambaram Stadium, Chepauk' 'Dr DY Patil Sports Academy' 'Newlands'
 "St George's Park" 'Kingsmead' 'SuperSport Park' 'Buffalo Park'
 'New Wanderers Stadium' 'De Beers Diamond Oval' 'OUTsurance Oval'
 'Brabourne Stadium' 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Brabourne Stadium, Mumbai'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Holkar Cricket Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Subrata Roy Sahara Stadium' 'Maharashtra Cricket Association Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex' 'Sheikh Zayed Stadium'
 'Sharjah Cricket Stadium' 'Dubai International Cricket Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'Saurashtra Cricket Association Stadium' 'Green Park'
 'M.Chinnaswamy Stadium' 'Punjab Cricket Association IS Bindra Stadium'
 'Rajiv Gandhi International Stadium' 'MA Chidambaram Stadium'
 'Arun Jaitley Stadium' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Wankhede Stadium, Mumbai' 'Narendra Modi Stadium, Ahmedabad'
 'Arun Jaitley Stadium, Delhi' 'Zayed Cricket Stadium, Abu Dhabi'
 'Dr DY Patil Sports Academy, Mumbai'
 'Maharashtra Cricket Association Stadium, Pune' 'Eden Gardens, Kolkata'
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'M Chinnaswamy Stadium, Bengaluru' 'Barsapara Cricket Stadium, Guwahati'
 'Sawai Mansingh Stadium, Jaipur'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala'
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']
The unique values in team1 are:  ['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']
The unique values in team2 are:  ['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
The unique values in toss_winner are:  ['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Gujarat Titans' 'Lucknow Super Giants'
 'Royal Challengers Bengaluru']
The unique values in toss_decision are:  ['field' 'bat']
The unique values in winner are:  ['Kolkata Knight Riders' 'Chennai Super Kings' 'Delhi Daredevils'
 'Royal Challengers Bangalore' 'Rajasthan Royals' 'Kings XI Punjab'
 'Deccan Chargers' 'Mumbai Indians' 'Pune Warriors' 'Kochi Tuskers Kerala'
 nan 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
The unique values in result are:  ['runs' 'wickets' 'tie' 'no result']
The unique values in result_margin are:  [140.  33.   9.   5.   6.   3.  66.   7.  10.   4.  13.  45.   8.  29.
  18.  23.  12.  65.  25.   1.  14.  41. 105.  19.  75.  92.  11.  24.
  nan  27.  38.  78.  16.  53.   2.  31.  55.  98.  34.  36.  17.  39.
  40.  67.  63.  37.  57.  35.  22.  21.  48.  26.  20.  85.  32.  76.
 111.  82.  43.  58.  28.  74.  42.  59.  46.  47.  86.  44.  87. 130.
  15.  60.  77.  30.  50.  93.  72.  62.  97. 138.  71. 144.  80.  51.

In [15]:
list2 = deliveries.columns.to_list()
remove_from_list2 = ['match_id', 'batsman', 'inning', 'non_striker', 
                     'bowler', 'player_dismissed', 'fielder']

In [16]:
missing2 = [col for col in remove_from_list2 if col not in deliveries.columns]
print("Missing columns from deliveries:", missing2)

Missing columns from deliveries: ['batsman']

In [17]:
missing = [col for col in remove_from_list if col not in matches.columns]
print("These columns were not in the DataFrame:", missing)

These columns were not in the DataFrame: ['win_by_runs', 'umpire3']

In [18]:
for i in list2:
    print('The unique values in', i, 'are: ', deliveries[i].unique())

The unique values in match_id are:  [ 335982  335983  335984 ... 1426310 1426311 1426312]
The unique values in inning are:  [1 2 3 4 5 6]
The unique values in batting_team are:  ['Kolkata Knight Riders' 'Royal Challengers Bangalore'
 'Chennai Super Kings' 'Kings XI Punjab' 'Rajasthan Royals'
 'Delhi Daredevils' 'Mumbai Indians' 'Deccan Chargers'
 'Kochi Tuskers Kerala' 'Pune Warriors' 'Sunrisers Hyderabad'
 'Rising Pune Supergiants' 'Gujarat Lions' 'Rising Pune Supergiant'
 'Delhi Capitals' 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']
The unique values in bowling_team are:  ['Royal Challengers Bangalore' 'Kolkata Knight Riders' 'Kings XI Punjab'
 'Chennai Super Kings' 'Delhi Daredevils' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
The unique values in over are:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The unique values in ball are:  [ 1  2  3  4  5  6  7  8  9 10 11]
The unique values in batter are:  ['SC Ganguly' 'BB McCullum' 'RT Ponting' 'DJ Hussey' 'Mohammad Hafeez'
 'R Dravid' 'W Jaffer' 'V Kohli' 'JH Kallis' 'CL White' 'MV Boucher'
 'B Akhil' 'AA Noffke' 'P Kumar' 'Z Khan' 'SB Joshi' 'PA Patel'
 'ML Hayden' 'MEK Hussey' 'MS Dhoni' 'SK Raina' 'JDP Oram' 'S Badrinath'
 'K Goel' 'JR Hopes' 'KC Sangakkara' 'Yuvraj Singh' 'SM Katich'
 'IK Pathan' 'T Kohli' 'YK Pathan' 'SR Watson' 'M Kaif' 'DS Lehmann'
 'RA Jadeja' 'M Rawat' 'D Salunkhe' 'SK Warne' 'SK Trivedi' 'G Gambhir'
 'V Sehwag' 'S Dhawan' 'L Ronchi' 'ST Jayasuriya' 'DJ Thornely'
 'RV Uthappa' 'PR Shah' 'AM Nayar' 'SM Pollock' 'Harbhajan Singh'
 'S Chanderpaul' 'LRPL Taylor' 'AC Gilchrist' 'Y Venugopal Rao'
 'VVS Laxman' 'A Symonds' 'RG Sharma' 'SB Styris' 'AS Yadav' 'SB Bangar'
 'WPUJC Vaas' 'RP Singh' 'WP Saha' 'LR Shukla' 'DPMD Jayawardene'
 'S Sohal' 'B Lee' 'PP Chawla' 'WA Mota' 'Kamran Akmal' 'Shahid Afridi'
 'DJ Bravo' 'MA Khote' 'A Nehra' 'GC Smith' 'Pankaj Singh' 'RR Sarwan'
 'S Sreesanth' 'VRV Singh' 'SS Tiwary' 'DS Kulkarni' 'R Vinay Kumar'
 'AB Agarkar' 'M Kartik' 'I Sharma' 'AM Rahane' 'Shoaib Malik' 'MK Tiwary'
 'KD Karthik' 'R Bhatia' 'MF Maharoof' 'VY Mahesh' 'TM Srivastava'
 'B Chipli' 'DW Steyn' 'DB Das' 'MK Pandey' 'HH Gibbs' 'DNT Zoysa'
 'D Kalyankrishna' 'SE Marsh' 'SA Asnodkar' 'Sohail Tanvir' 'Salman Butt'
 'BJ Hodge' 'Umar Gul' 'AB Dinda' 'SP Fleming' 'S Vidyut' 'JA Morkel'
 'AB de Villiers' 'LPC Silva' 'DB Ravi Teja' 'Misbah-ul-Haq' 'YV Takawale'
 'RR Raje' 'PJ Sangwan' 'Mohammad Asif' 'GD McGrath' 'Joginder Sharma'
 'MS Gony' 'M Muralitharan' 'M Ntini' 'DT Patil' 'A Kumble' 'S Anirudha'
 'MM Patel' 'CK Kapugedera' 'A Chopra' 'T Taibu' 'J Arunkumar' 'PP Ojha'
 'SP Goswami' 'SR Tendulkar' 'U Kaul' 'TM Dilshan' 'A Mishra'
 'AD Mascarenhas' 'NK Patel' 'LA Pomersbach' 'Iqbal Abdulla' 'Younis Khan'
 'PM Sarvesh Kumar' 'DP Vijaykumar' 'Shoaib Akhtar' 'Abdur Razzak' 'H Das'
 'DR Smith' 'SD Chitnis' 'CRD Fernando' 'VS Yeligati' 'L Balaji'
 'A Mukund' 'RR Powar' 'JP Duminy' 'A Flintoff' 'T Thushara' 'JD Ryder'
 'KP Pietersen' 'T Henderson' 'Kamran Khan' 'RS Bopara' 'CH Gayle'
 'MC Henriques' 'R Bishnoi' 'FH Edwards' 'KV Sharma' 'PC Valthaty'
 'RJ Quiney' 'AS Raut' 'Yashpal Singh' 'M Manhas' 'AA Bilakhia' 'AN Ghosh'
 'BAW Mendis' 'DL Vettori' 'MN van Wyk' 'RE van der Merwe' 'TL Suman'
 'Shoaib Ahmed' 'GR Napier' 'KP Appanna' 'LA Carseldine' 'NV Ojha'
 'SM Harwood' 'M Vijay' 'SB Jakati' 'DA Warner' 'RJ Harris' 'D du Preez'
 'M Morkel' 'AD Mathews' 'J Botha' 'C Nanda' 'SL Malinga'
 'Mashrafe Mortaza' 'A Singh' 'GJ Bailey' 'AB McDonald' 'Y Nagar'
 'SS Shaikh' 'R Ashwin' 'Mohammad Ashraful' 'CA Pujara' 'OA Shah'
 'Anirudh Singh' 'Jaskaran Singh' 'AP Tare' 'AT Rayudu' 'R Sathish'
 'R McLaren' 'AA Jhunjhunwala' 'P Dogra' 'A Uniyal' 'MS Bisla'
 'YA Abdulla' 'EJG Morgan' 'JM Kemp' 'S Tyagi' 'RS Gavaskar' 'SE Bond'
 'KA Pollard' 'S Ladda' 'DP Nannes' 'MJ Lumb' 'DR Martyn' 'S Narwal'
 'AB Barath' 'Bipul Sharma' 'FY Fazal' 'AC Voges' 'MD Mishra' 'UT Yadav'
 'J Theron' 'SJ Srivastava' 'R Sharma' 'Mandeep Singh' 'KM Jadhav'
 'SW Tait' 'KB Arun Karthik' 'KAJ Roach' 'PD Collingwood' 'CK Langeveldt'
 'VS Malik' 'A Mithun' 'AP Dole' 'AN Ahmed' 'RS Sodhi' 'DE Bollinger'
 'S Sriram' 'B Sumanth' 'C Madan' 'AG Paunikar' 'MR Marsh' 'AJ Finch'
 'STR Binny' 'Harmeet Singh' 'IR Jaggi' 'DT Christian' 'RV Gomez'
 'MA Agarwal' 'AUK Pathan' 'UBT Chand' 'DJ Jacobs' 'Sunny Singh'
 'NJ Rimmington' 'AL Menaria' 'WD Parnell' 'JJ van der Wath' 'R Ninan'
 'S Aravind' 'MS Wade' 'TD Paine' 'SB Wagh' 'AC Thomas' 'JEC Franklin'
 'Shakib Al Hasan' 'DH Yagnik' 'S Randiv' 'BJ Haddin' 'NLTC Perera'
 'NL McCullum' 'JE Taylor' 'J Syed Mohammad' 'RN ten Doeschate' 'TR Birt'
 'AG Murtaza' 'Harpreet Singh' 'M Klinger' 'AC Blizzard' 'I Malhotra'
 'L Ablish' 'CA Ingram' 'S Nadeem' 'P Parameswaran' 'CJ Ferguson'
 'VR Aaron' 'AA Chavan' 'ND Doshi' 'B Kumar' 'Y Gnaneswara Rao' 'S Rana'
 'BA Bhatt' 'F du Plessis' 'RE Levi' 'GJ Maxwell' 'SPD Smith' 'MN Samuels'
 'SA Yadav' 'KK Cooper' 'JP Faulkner' 'HV Patel' 'DAJ Bracewell'
 'DJ Harris' 'Ankit Sharma' 'SP Narine' 'GB Hogg' 'RR Bhatkal' 'CJ McKay'
 'N Saini' 'DA Miller' 'Azhar Mahmood' 'P Negi' 'RJ Peterson'
 'KMDN Kulasekara' 'A Ashish Reddy' 'V Pratap Singh' 'BB Samantray'
 'MJ Clarke' 'Gurkeerat Singh' 'AP Majumdar' 'PA Reddy' 'K Upadhyay'
 'P Awana' 'AD Russell' 'A Chandila' 'CA Lynn' 'Sunny Gupta' 'MC Juneja'
 'KK Nair' 'GH Vihari' 'MDKJ Perera' 'R Shukla' 'B Laughlin' 'AS Rajpoot'
 'M Vohra' 'JD Unadkat' 'Mohammed Shami' 'BMAJ Mendis' 'R Rampaul'
 'CH Morris' 'SV Samson' 'SMSM Senanayake' 'BJ Rohrer' 'KL Rahul'
 'Q de Kock' 'R Dhawan' 'MG Johnson' 'LJ Wright' 'IC Pandey' 'CM Gautam'
 'X Thalaivan Sargunam' 'DJG Sammy' 'KW Richardson' 'MM Sharma' 'UA Birla'
 'Parvez Rasool' 'Sandeep Sharma' 'S Kaul' 'Sachin Baby' 'PV Tambe'
 'NM Coulter-Nile' 'CJ Anderson' 'NJ Maddinson' 'AR Patel' 'JJ Bumrah'
 'JDS Neesham' 'TG Southee' 'MA Starc' 'BR Dunk' 'RR Rossouw'
 'Shivam Sharma' 'YS Chahal' 'LMP Simmons' 'VH Zol' 'BCJ Cutting'
 'Imran Tahir' 'BE Hendricks' 'S Gopal' 'M de Lange' 'R Tewatia'
 'JO Holder' 'Karanveer Singh' 'SS Iyer' 'DJ Hooda' 'Anureet Singh'
 'KS Williamson' 'SA Abbott' 'J Suchith' 'RG More' 'HH Pandya' 'D Wiese'
 'SN Khan' 'MJ McClenaghan' 'DJ Muthuswami' 'PJ Cummins' 'SN Thakur'
 'JC Buttler' 'CR Brathwaite' 'MP Stoinis' 'Ishan Kishan' 'C Munro'
 'P Sahu' 'KH Pandya' 'AD Nath' 'MJ Guptill' 'KJ Abbott' 'TM Head'
 'M Ashwin' 'NS Naik' 'RR Pant' 'SW Billings' 'KC Cariappa'
 'PSP Handscomb' 'Swapnil Singh' 'J Yadav' 'UT Khawaja' 'HM Amla'
 'F Behardien' 'BB Sran' 'A Zampa' 'N Rana' 'S Kaushik' 'ER Dwivedi'
 'CJ Jordan' 'TS Mills' 'A Choudhary' 'BA Stokes' 'JJ Roy' 'Vishnu Vinod'
 'Basil Thampi' 'CR Woakes' 'RA Tripathi' 'DL Chahar' 'V Shankar'
 'Rashid Khan' 'RD Chahar' 'LH Ferguson' 'C de Grandhomme' 'AF Milne'
 'S Badree' 'Mohammad Nabi' 'AJ Tye' 'K Rabada' 'Kuldeep Yadav'
 'Washington Sundar' 'DM Bravo' 'AR Bawne' 'SP Jackson' 'Ankit Soni'
 'TA Boult' 'E Lewis' 'MA Wood' 'RK Singh' 'DJM Short' 'K Gowtham'
 'TK Curran' 'M Markande' 'B Stanlake' 'Mujeeb Ur Rahman' 'A Dananjaya'
 'Shubman Gill' 'Shivam Mavi' 'Mohammed Siraj' 'H Klaasen' 'RK Bhui'
 'JC Archer' 'PP Shaw' 'LE Plunkett' 'Mustafizur Rahman' 'AD Hales'
 'MK Lomror' 'DR Shorey' 'MM Ali' 'M Prasidh Krishna' 'P Chopra'
 'JPR Scantlebury-Searles' 'Abhishek Sharma' 'IS Sodhi' 'SO Hetmyer'
 'S Dube' 'Navdeep Saini' 'JM Bairstow' 'KMA Paul' 'Rasikh Salam'
 'N Pooran' 'P Ray Barman' 'SM Curran' 'GC Viljoen' 'Avesh Khan'
 'S Lamichhane' 'HF Gurney' 'SD Lad' 'AS Joseph' 'R Parag' 'MJ Santner'
 'JL Denly' 'LS Livingstone' 'KK Ahmed' 'AJ Turner' 'Harpreet Brar'
 'SE Rutherford' 'Y Prithvi Raj' 'P Simran Singh' 'JL Pattinson'
 'A Nortje' 'T Banton' 'D Padikkal' 'YBK Jaiswal' 'RD Gaikwad'
 'TU Deshpande' 'Abdul Samad' 'PK Garg' 'JR Philippe' 'Kartik Tyagi'
 'KL Nagarkoti' 'CV Varun' 'I Udana' 'Ravi Bishnoi' 'Shahbaz Ahmed'
 'AT Carey' 'N Jagadeesan' 'T Natarajan' 'P Dubey' 'SS Cottrell'
 'Arshdeep Singh' 'DR Sams' 'M Jansen' 'RM Patidar' 'KA Jamieson'
 'M Shahrukh Khan' 'JA Richardson' 'Lalit Yadav' 'Virat Singh' 'FA Allen'
 'C Sakariya' 'DJ Malan' 'KS Bharat' 'PWH de Silva' 'VR Iyer'
 'GD Phillips' 'GHS Garton' 'AK Markram' 'K Yadav' 'T Shamsi' 'NT Ellis'
 'RV Patel' 'TL Seifert' 'Anmolpreet Singh' 'Anuj Rawat' 'TH David'
 'DP Conway' 'Tilak Varma' 'R Powell' 'PBB Rajapaksa' 'RA Bawa' 'OF Smith'
 'A Badoni' 'PVD Chameera' 'A Manohar' 'R Shepherd' 'DJ Willey'
 'D Pretorius' 'JM Sharma' 'VG Arora' 'Mukesh Choudhary' 'Umran Malik'
 'D Brevis' 'B Sai Sudharsan' 'Ramandeep Singh' 'HE van der Dussen'
 'SS Prabhudessai' 'Akash Deep' 'JR Hazlewood' 'KR Sen' 'Aman Hakim Khan'
 'HR Shokeen' 'Yash Dayal' 'DJ Mitchell' 'Shashank Singh' 'B Indrajith'
 'Harshit Rana' 'Mohsin Khan' 'Simarjeet Singh' 'M Theekshana' 'AS Roy'
 'Fazalhaq Farooqi' 'K Kartikeya' 'RP Meredith' 'KS Sharma' 'T Stubbs'
 'R Sanjay Yadav' 'A Tomar' 'PN Mankad' 'OC McCoy' 'Sikandar Raza'
 'Rahmanullah Gurbaz' 'KR Mayers' 'Mukesh Kumar' 'HC Brook' 'AU Rashid'
 'C Green' 'N Wadhera' 'Arshad Khan' 'Abishek Porel' 'Dhruv Jurel'
 'MG Bracewell' 'MW Short' 'Mohit Rathee' 'YV Dhull' 'Yudhvir Singh'
 'Atharva Taide' 'Liton Das' 'PD Salt' 'Vijaykumar Vyshak' 'Abdul Basith'
 'Arjun Tendulkar' 'JP Behrendorff' 'AJ Hosein' 'Naveen-ul-Haq'
 'Noor Ahmad' 'JE Root' 'KM Asif' 'MD Shanaka' 'Sanvir Singh'
 'Vivrant Sharma' 'DG Nalkande' 'R Ravindra' 'SD Hope' 'Sumit Kumar'
 'Azmatullah Omarzai' 'Naman Dhir' 'G Coetzee' 'SZ Mulani' 'Sameer Rizvi'
 'SH Johnson' 'Akash Madhwal' 'SB Dubey' 'Mayank Dagar' 'RJW Topley'
 'A Raghuvanshi' 'Ashutosh Sharma' 'Nithish Kumar Reddy' 'Saurav Chauhan'
 'Kumar Kushagra' 'BR Sharath' 'WG Jacks' 'J Fraser-McGurk'
 'Tanush Kotian' 'KA Maharaj' 'Arshad Khan (2)' 'R Sai Kishore' 'L Wood'
 'LB Williams' 'AA Kulkarni' 'MJ Suthar' 'RJ Gleeson' 'Gulbadin Naib'
 'D Ferreira' 'A Kamboj' 'T Kohler-Cadmore' 'Shivam Singh' 'V Viyaskanth']
The unique values in bowler are:  ['P Kumar' 'Z Khan' 'AA Noffke' 'JH Kallis' 'SB Joshi' 'CL White'
 'AB Dinda' 'I Sharma' 'AB Agarkar' 'SC Ganguly' 'LR Shukla' 'B Lee'
 'S Sreesanth' 'JR Hopes' 'IK Pathan' 'K Goel' 'PP Chawla' 'WA Mota'
 'JDP Oram' 'MS Gony' 'M Muralitharan' 'P Amarnath' 'Joginder Sharma'
 'GD McGrath' 'B Geeves' 'MF Maharoof' 'R Bhatia' 'DL Vettori' 'MM Patel'
 'SR Watson' 'SK Trivedi' 'SK Warne' 'YK Pathan' 'D Salunkhe'
 'R Vinay Kumar' 'B Akhil' 'A Nehra' 'SM Pollock' 'DS Kulkarni'
 'ST Jayasuriya' 'Harbhajan Singh' 'AM Nayar' 'M Kartik' 'Mohammad Hafeez'
 'DJ Hussey' 'WPUJC Vaas' 'RP Singh' 'SB Styris' 'SB Bangar' 'A Symonds'
 'PP Ojha' 'Pankaj Singh' 'Mohammad Asif' 'VY Mahesh' 'Shahid Afridi'
 'DJ Bravo' 'VS Yeligati' 'MA Khote' 'D Kalyankrishna' 'VRV Singh'
 'Sohail Tanvir' 'A Kumble' 'DNT Zoysa' 'SD Chitnis' 'Yuvraj Singh'
 'Shoaib Malik' 'DW Steyn' 'JA Morkel' 'CRD Fernando' 'V Kohli' 'V Sehwag'
 'Gagandeep Singh' 'Y Venugopal Rao' 'Umar Gul' 'PJ Sangwan' 'M Ntini'
 'DP Vijaykumar' 'DB Ravi Teja' 'LPC Silva' 'DJ Thornely' 'RR Raje'
 'SK Raina' 'S Vidyut' 'L Balaji' 'CK Kapugedera' 'DR Smith'
 'AD Mascarenhas' 'A Mishra' 'Shoaib Akhtar' 'Iqbal Abdulla' 'RR Powar'
 'PM Sarvesh Kumar' 'Abdur Razzak' 'RA Jadeja' 'TM Dilshan' 'RG Sharma'
 'A Nel' 'BAW Mendis' 'T Thushara' 'A Flintoff' 'SL Malinga' 'Kamran Khan'
 'T Henderson' 'JD Ryder' 'DP Nannes' 'AM Salvi' 'YA Abdulla' 'VS Malik'
 'FH Edwards' 'Harmeet Singh' 'CH Gayle' 'MC Henriques' 'KP Pietersen'
 'LRPL Taylor' 'RS Bopara' 'MK Tiwary' 'Anureet Singh' 'RR Bose'
 'KP Appanna' 'Shoaib Ahmed' 'BJ Hodge' 'SR Tendulkar' 'RE van der Merwe'
 'JP Duminy' 'S Tyagi' 'GR Napier' 'SM Harwood' 'AS Raut' 'SB Jakati'
 'D du Preez' 'RJ Harris' 'TL Suman' 'A Singh' 'M Morkel' 'LA Carseldine'
 'A Mithun' 'C Nanda' 'SS Sarkar' 'AD Mathews' 'AM Rahane' 'J Botha'
 'Mashrafe Mortaza' 'AB McDonald' 'Y Nagar' 'CK Langeveldt' 'R Ashwin'
 'RA Shaikh' 'Jaskaran Singh' 'SW Tait' 'A Uniyal' 'AA Jhunjhunwala'
 'R McLaren' 'AG Murtaza' 'R Sathish' 'RS Gavaskar' 'JM Kemp' 'S Ladda'
 'Bipul Sharma' 'SE Bond' 'KA Pollard' 'S Narwal' 'UT Yadav'
 'SJ Srivastava' 'AC Voges' 'R Sharma' 'J Theron' 'NLTC Perera'
 'KAJ Roach' 'PD Collingwood' 'C Ganapathy' 'MB Parmar' 'SB Wagh'
 'DE Bollinger' 'JD Unadkat' 'AP Dole' 'AN Ahmed' 'FY Fazal' 'MR Marsh'
 'L Ablish' 'S Sriram' 'AJ Finch' 'STR Binny' 'ND Doshi' 'TG Southee'
 'S Randiv' 'AL Menaria' 'DT Christian' 'AUK Pathan' 'RV Gomez'
 'JEC Franklin' 'AC Thomas' 'WD Parnell' 'M Manhas' 'NJ Rimmington'
 'RN ten Doeschate' 'S Nadeem' 'BA Bhatt' 'JJ van der Wath' 'S Aravind'
 'R Ninan' 'Shakib Al Hasan' 'PC Valthaty' 'S Dhawan' 'J Syed Mohammad'
 'VR Aaron' 'NL McCullum' 'JE Taylor' 'KMDN Kulasekara' 'P Parameswaran'
 'I Malhotra' 'B Chipli' 'B Kumar' 'AA Kazi' 'Anand Rajan' 'P Prasanth'
 'Y Gnaneswara Rao' 'AA Chavan' 'S Rana' 'JP Faulkner' 'SS Mundhe'
 'RW Price' 'GJ Maxwell' 'M de Lange' 'MN Samuels' 'KK Cooper'
 'DAJ Bracewell' 'HV Patel' 'Ankit Sharma' 'DJ Harris' 'TP Sudhindra'
 'F du Plessis' 'SP Narine' 'GB Hogg' 'RR Bhatkal' 'P Awana'
 'V Pratap Singh' 'CJ McKay' 'AD Russell' 'A Ashish Reddy' 'Azhar Mahmood'
 'A Chandila' 'P Negi' 'LJ Wright' 'RJ Peterson' 'R Shukla' 'MJ Clarke'
 'BW Hilfenhaus' 'SPD Smith' 'K Upadhyay' 'Sunny Gupta' 'MG Johnson'
 'JJ Bumrah' 'S Badree' 'AS Rajpoot' 'B Laughlin' 'GH Vihari'
 'Mohammed Shami' 'BMAJ Mendis' 'CH Morris' 'S Kaul' 'R Dhawan'
 'MM Sharma' 'R Rampaul' 'KV Sharma' 'SMSM Senanayake' 'JO Holder'
 'IC Pandey' 'Sandeep Sharma' 'YS Chahal' 'DJG Sammy' 'KW Richardson'
 'P Suyal' 'PV Tambe' 'BJ Rohrer' 'Parvez Rasool' 'MG Neser'
 'NM Coulter-Nile' 'AC Gilchrist' 'CJ Anderson' 'MA Starc' 'JDS Neesham'
 'AR Patel' 'M Vijay' 'R Tewatia' 'SA Yadav' 'Shivam Sharma' 'Imran Tahir'
 'V Shankar' 'LMP Simmons' 'BCJ Cutting' 'K Santokie' 'S Gopal'
 'BE Hendricks' 'PJ Cummins' 'JW Hastings' 'Karanveer Singh'
 'DJ Muthuswami' 'TA Boult' 'SA Abbott' 'KC Cariappa' 'DJ Hooda'
 'J Suchith' 'RG More' 'D Wiese' 'MJ McClenaghan' 'HH Pandya' 'SN Thakur'
 'GS Sandhu' 'Gurkeerat Singh' 'J Yadav' 'BB Sran' 'M Ashwin' 'C Munro'
 'CR Brathwaite' 'MP Stoinis' 'P Sahu' 'Mustafizur Rahman' 'AF Milne'
 'Kuldeep Yadav' 'KH Pandya' 'KJ Abbott' 'T Shamsi' 'S Kaushik'
 'SM Boland' 'Swapnil Singh' 'CJ Jordan' 'A Zampa' 'Sachin Baby' 'N Rana'
 'DL Chahar' 'KS Williamson' 'TS Mills' 'A Choudhary' 'TM Head'
 'Rashid Khan' 'BA Stokes' 'CR Woakes' 'T Natarajan' 'RD Chahar'
 'B Stanlake' 'Tejas Baroka' 'Basil Thampi' 'C de Grandhomme' 'AJ Tye'
 'LH Ferguson' 'Mohammad Nabi' 'Mohammed Siraj' 'K Rabada'
 'Washington Sundar' 'SS Agarwal' 'NB Singh' 'RA Tripathi' 'Ankit Soni'
 'MJ Henry' 'Avesh Khan' 'MA Wood' 'M Markande' 'Mujeeb Ur Rahman'
 'K Khejroliya' 'K Gowtham' 'DJM Short' 'TK Curran' 'A Dananjaya'
 'Shivam Mavi' 'JC Archer' 'LE Plunkett' 'IS Sodhi' 'MK Lomror' 'L Ngidi'
 'KM Asif' 'DJ Willey' 'M Prasidh Krishna' 'MM Ali'
 'JPR Scantlebury-Searles' 'S Lamichhane' 'CJ Dala' 'KK Ahmed'
 'Navdeep Saini' 'S Dube' 'Rasikh Salam' 'KMA Paul' 'SM Curran' 'CV Varun'
 'GC Viljoen' 'Mandeep Singh' 'P Ray Barman' 'MJ Santner' 'JP Behrendorff'
 'SC Kuggeleijn' 'AS Joseph' 'HF Gurney' 'S Midhun' 'R Parag'
 'LS Livingstone' 'SN Khan' 'Abhishek Sharma' 'Arshdeep Singh'
 'SE Rutherford' 'Harpreet Brar' 'Y Prithvi Raj' 'O Thomas' 'AS Roy'
 'S Sandeep Warrier' 'JL Pattinson' 'SS Cottrell' 'Ravi Bishnoi'
 'A Nortje' 'I Udana' 'TU Deshpande' 'KL Nagarkoti' 'Kartik Tyagi'
 'DR Sams' 'Shahbaz Ahmed' 'Abdul Samad' 'JR Hazlewood' 'DA Warner'
 'CJ Green' 'P Dubey' 'Monu Kumar' 'KA Jamieson' 'M Jansen' 'C Sakariya'
 'JA Richardson' 'RP Meredith' 'LI Meriwala' 'Lalit Yadav'
 'Jalaj S Saxena' 'FA Allen' 'PWH de Silva' 'Umran Malik' 'Akash Singh'
 'GD Phillips' 'AK Markram' 'GHS Garton' 'VR Iyer' 'K Yadav' 'NT Ellis'
 'RV Patel' 'IC Porel' 'AU Rashid' 'OF Smith' 'Akash Deep' 'PVD Chameera'
 'Mohsin Khan' 'R Shepherd' 'Mukesh Choudhary' 'D Pretorius' 'VG Arora'
 'YBK Jaiswal' 'Tilak Varma' 'DG Nalkande' 'M Theekshana' 'D Brevis'
 'R Powell' 'KR Sen' 'Yash Dayal' 'Shashank Singh' 'Aman Hakim Khan'
 'OC McCoy' 'HR Shokeen' 'A Badoni' 'DJ Mitchell' 'Harshit Rana' 'SS Iyer'
 'K Kartikeya' 'Simarjeet Singh' 'Fazalhaq Farooqi' 'R Sai Kishore'
 'Ramandeep Singh' 'PH Solanki' 'M Pathirana' 'R Sanjay Yadav' 'J Little'
 'RS Hangargekar' 'Sikandar Raza' 'Mukesh Kumar' 'KR Mayers' 'NA Saini'
 'RJW Topley' 'MG Bracewell' 'Arshad Khan' 'C Green' 'Yash Thakur'
 'Suyash Sharma' 'SSB Magala' 'Mohit Rathee' 'MW Short'
 'Vijaykumar Vyshak' 'Yudhvir Singh' 'Arjun Tendulkar' 'D Jansen'
 'Noor Ahmad' 'Naveen-ul-Haq' 'Mayank Dagar' 'Gurnoor Brar' 'AJ Hosein'
 'Akash Madhwal' 'R Goyal' 'T Stubbs' 'Vivrant Sharma' 'JE Root'
 'Nithish Kumar Reddy' 'H Sharma' 'Sumit Kumar' 'N Burger' 'L Wood'
 'SZ Mulani' 'Naman Dhir' 'G Coetzee' 'Azmatullah Omarzai' 'SH Johnson'
 'KT Maphaka' 'M Siddharth' 'MP Yadav' 'R Ravindra' 'KA Maharaj'
 'WG Jacks' 'S Joseph' 'Arshad Khan (2)' 'M Shahrukh Khan' 'N Thushara'
 'LB Williams' 'RJ Gleeson' 'MJ Suthar' 'A Kamboj' 'V Viyaskanth'
 'V Kaverappa' 'Gulbadin Naib' 'N Wadhera' 'Atharva Taide']
The unique values in non_striker are:  ['BB McCullum' 'SC Ganguly' 'RT Ponting' 'DJ Hussey' 'Mohammad Hafeez'
 'W Jaffer' 'R Dravid' 'V Kohli' 'JH Kallis' 'CL White' 'MV Boucher'
 'B Akhil' 'AA Noffke' 'P Kumar' 'Z Khan' 'SB Joshi' 'ML Hayden'
 'PA Patel' 'MEK Hussey' 'MS Dhoni' 'SK Raina' 'JDP Oram' 'S Badrinath'
 'JR Hopes' 'K Goel' 'KC Sangakkara' 'Yuvraj Singh' 'SM Katich'
 'IK Pathan' 'YK Pathan' 'T Kohli' 'SR Watson' 'M Kaif' 'DS Lehmann'
 'RA Jadeja' 'M Rawat' 'D Salunkhe' 'SK Warne' 'SK Trivedi' 'V Sehwag'
 'G Gambhir' 'S Dhawan' 'ST Jayasuriya' 'L Ronchi' 'DJ Thornely'
 'RV Uthappa' 'PR Shah' 'AM Nayar' 'SM Pollock' 'Harbhajan Singh'
 'S Chanderpaul' 'LRPL Taylor' 'Y Venugopal Rao' 'AC Gilchrist'
 'VVS Laxman' 'A Symonds' 'SB Styris' 'AS Yadav' 'SB Bangar' 'WPUJC Vaas'
 'RP Singh' 'PP Ojha' 'WP Saha' 'LR Shukla' 'DPMD Jayawardene' 'S Sohal'
 'PP Chawla' 'WA Mota' 'Kamran Akmal' 'RG Sharma' 'Shahid Afridi'
 'DJ Bravo' 'MA Khote' 'A Nehra' 'GC Smith' 'Pankaj Singh' 'RR Sarwan'
 'B Lee' 'S Sreesanth' 'VRV Singh' 'SS Tiwary' 'DS Kulkarni'
 'R Vinay Kumar' 'AB Agarkar' 'M Kartik' 'I Sharma' 'AB Dinda' 'AM Rahane'
 'Shoaib Malik' 'MK Tiwary' 'KD Karthik' 'R Bhatia' 'MF Maharoof'
 'VY Mahesh' 'TM Srivastava' 'B Chipli' 'DW Steyn' 'DB Das' 'MK Pandey'
 'HH Gibbs' 'DNT Zoysa' 'D Kalyankrishna' 'SE Marsh' 'SA Asnodkar'
 'Sohail Tanvir' 'Salman Butt' 'BJ Hodge' 'Umar Gul' 'SP Fleming'
 'S Vidyut' 'JA Morkel' 'Joginder Sharma' 'AB de Villiers' 'LPC Silva'
 'DB Ravi Teja' 'DP Vijaykumar' 'Misbah-ul-Haq' 'YV Takawale' 'RR Raje'
 'PJ Sangwan' 'Mohammad Asif' 'GD McGrath' 'MS Gony' 'M Ntini' 'DT Patil'
 'A Kumble' 'S Anirudha' 'MM Patel' 'CK Kapugedera' 'A Chopra' 'T Taibu'
 'J Arunkumar' 'SP Goswami' 'SR Tendulkar' 'TM Dilshan' 'A Mishra'
 'AD Mascarenhas' 'NK Patel' 'LA Pomersbach' 'Iqbal Abdulla' 'Younis Khan'
 'PM Sarvesh Kumar' 'Shoaib Akhtar' 'Abdur Razzak' 'H Das' 'DR Smith'
 'SD Chitnis' 'CRD Fernando' 'A Nel' 'RR Powar' 'JP Duminy' 'A Flintoff'
 'KP Pietersen' 'T Henderson' 'Kamran Khan' 'RS Bopara' 'CH Gayle'
 'MC Henriques' 'R Bishnoi' 'FH Edwards' 'KV Sharma' 'DL Vettori'
 'L Balaji' 'M Muralitharan' 'PC Valthaty' 'AS Raut' 'Yashpal Singh'
 'JD Ryder' 'M Manhas' 'RJ Quiney' 'AA Bilakhia' 'AN Ghosh' 'BAW Mendis'
 'MN van Wyk' 'RE van der Merwe' 'TL Suman' 'GR Napier' 'KP Appanna'
 'LA Carseldine' 'NV Ojha' 'SM Harwood' 'M Vijay' 'SB Jakati' 'S Tyagi'
 'DA Warner' 'RJ Harris' 'Shoaib Ahmed' 'D du Preez' 'SL Malinga'
 'M Morkel' 'AD Mathews' 'J Botha' 'Mashrafe Mortaza' 'Jaskaran Singh'
 'GJ Bailey' 'AB McDonald' 'Y Nagar' 'A Singh' 'SS Shaikh' 'R Ashwin'
 'T Thushara' 'Mohammad Ashraful' 'CA Pujara' 'OA Shah' 'Anirudh Singh'
 'AP Tare' 'AT Rayudu' 'R Sathish' 'R McLaren' 'AA Jhunjhunwala' 'P Dogra'

In [19]:
# grouping the 1st innings,2nd innings score in a particular matchid
# lets say match id = 1,so inning 1 score = 207,inning 2 score = 172

totalrun_df=deliveries.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

totalrun_df

      match_id  inning  total_runs
0       335982       1         222
1       335982       2          82
2       335983       1         240
3       335983       2         207
4       335984       1         129
...        ...     ...         ...
2212   1426310       2         174
2213   1426311       1         175
2214   1426311       2         139
2215   1426312       1         113
2216   1426312       2         114

[2217 rows x 3 columns]

In [20]:
#capturing only the first innings, because we will be predicting the second innings
#Also we are changing total runs into targets by using the lambda function

totalrun_df = totalrun_df[totalrun_df['inning']==1].copy()
totalrun_df['total_runs'] = totalrun_df['total_runs'].apply(lambda x:x+1)#to get target
totalrun_df

      match_id  inning  total_runs
0       335982       1         223
2       335983       1         241
4       335984       1         130
6       335985       1         166
8       335986       1         111
...        ...     ...         ...
2207   1426307       1         215
2209   1426309       1         160
2211   1426310       1         173
2213   1426311       1         176
2215   1426312       1         114

[1095 rows x 3 columns]

In [21]:
match_df = matches.merge(totalrun_df[['match_id','total_runs']],
                       left_on='id',right_on='match_id')

match_df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,match_id,total_runs
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,335982,223
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,335983,241
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,335984,130
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,335985,166
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,335986,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,1426307,215
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,1426309,160
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,1426310,173
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,1426311,176
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,1426312,114

In [22]:
match_df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [23]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

In [24]:
# replacing the Delhi Daredevils with Delhi Capitals

match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

# replacing the Deccan Chargers with Sunrises Hyderabad

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [25]:
# considering only frequently occurring teams,
# which are mentioned in the team's list

match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

match_df['team1'].unique() #again checking unique team names from match_df

array(['Royal Challengers Bangalore', 'Kings XI Punjab', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Chennai Super Kings'], dtype=object)

In [26]:
pip install jinja2

Requirement already satisfied: jinja2 in c:\users\hp\anaconda3\envs\py3_env\lib\site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\envs\py3_env\lib\site-packages (from jinja2) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
# checking the matches which resulted in the DL method
match_df[match_df['method'] == 'D/L'].style.background_gradient(cmap='plasma')

In [28]:
print(match_df.columns.to_list())

['id', 'season', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2', 'match_id', 'total_runs']

In [29]:
# ignoring the rows where Duckworth-Lewis method was used
match_df = match_df[match_df['method'].isna()]

# considering the match_id, city, winner, and total runs
match_df = match_df[['match_id', 'city', 'winner', 'total_runs']]

match_df

      match_id        city                       winner  total_runs
0       335982   Bangalore        Kolkata Knight Riders         223
1       335983  Chandigarh          Chennai Super Kings         241
2       335984       Delhi             Delhi Daredevils         130
3       335985      Mumbai  Royal Challengers Bangalore         166
4       335986     Kolkata        Kolkata Knight Riders         111
...        ...         ...                          ...         ...
1083   1426298     Kolkata        Kolkata Knight Riders         158
1084   1426299     Chennai          Chennai Super Kings         142
1091   1426309   Ahmedabad        Kolkata Knight Riders         160
1093   1426311     Chennai          Sunrisers Hyderabad         176
1094   1426312     Chennai        Kolkata Knight Riders         114

[824 rows x 4 columns]

In [30]:
#merging matchdf with deliveries on match_id

delivery_df = match_df.merge(deliveries,on='match_id')

delivery_df.head(5)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [31]:
delivery_df.columns

Index(['match_id', 'city', 'winner', 'total_runs_x', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs_y', 'extras_type',
       'is_wicket', 'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [32]:
delivery_df.shape

(197397, 20)

In [33]:
# to get the current score of a particular match

delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()

delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batter,...,non_striker,batsman_runs,extra_runs,total_runs_y,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
0,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,...,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,1
1,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,...,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,1
2,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,...,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN,2
3,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,...,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,2
4,335982,Bangalore,Kolkata Knight Riders,223,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,...,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,2

In [34]:
# creating column for runs left 

delivery_df['runs_left'] = delivery_df['total_runs_x']-delivery_df['current_score']

delivery_df[['total_runs_x', 'current_score', 'runs_left']].head()

   total_runs_x  current_score  runs_left
0           223              1        222
1           223              1        222
2           223              2        221
3           223              2        221
4           223              2        221

In [35]:
# creating a column for balls left

delivery_df['balls_left'] = 120-(delivery_df['over']*6+delivery_df['ball'])

delivery_df[['over', 'ball', 'balls_left']].head(10)

   over  ball  balls_left
0     0     1         119
1     0     2         118
2     0     3         117
3     0     4         116
4     0     5         115
5     0     6         114
6     0     7         113
7     1     1         113
8     1     2         112
9     1     3         111

In [36]:
delivery_df['player_dismissed']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
197392    NaN
197393    NaN
197394    NaN
197395    NaN
197396    NaN
Name: player_dismissed, Length: 197397, dtype: object

In [37]:
# filling nan values with "0"

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")

# now we will convert this player_dismissed col into a boolean col
# if the player is not dismissed then it's 0 else it's 1

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x
                                                                      if x=="0" else "1")

# converting string to int

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')


delivery_df['player_dismissed'].unique()

array([0, 1])

In [38]:
# Calculate cumulative sum of dismissals per match
delivery_df['wickets'] = delivery_df.groupby('match_id')['player_dismissed'].cumsum()

# Subtract from 10 to get wickets left
delivery_df['wickets_left'] = 10 - delivery_df['wickets']

In [39]:
delivery_df[['match_id', 'player_dismissed', 'wickets', 'wickets_left']].head(10)

   match_id  player_dismissed  wickets  wickets_left
0    335982                 0        0            10
1    335982                 0        0            10
2    335982                 0        0            10
3    335982                 0        0            10
4    335982                 0        0            10
5    335982                 0        0            10
6    335982                 0        0            10
7    335982                 0        0            10
8    335982                 0        0            10
9    335982                 0        0            10

In [40]:
# current RunRate
# It is a common practice to express run rates in cricket which means to 
#express it in runs per over, 
# so the score is multiplied by 6.

delivery_df['cur_run_rate'] = (delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

# required Run-Rate

delivery_df['req_run_rate'] = (delivery_df['runs_left']*6)/(delivery_df['balls_left'])

#Current Run-Rate
delivery_df[['cur_run_rate', 'req_run_rate']].head(10)

   cur_run_rate  req_run_rate
0      6.000000     11.193277
1      3.000000     11.288136
2      4.000000     11.333333
3      3.000000     11.431034
4      2.400000     11.530435
5      2.000000     11.631579
6      2.571429     11.681416
7      2.571429     11.681416
8      5.250000     11.571429
9      7.333333     11.459459

In [41]:
def resultofmatch(row):
    
    return 1 if row['batting_team'] == row['winner'] else 0
    
delivery_df['result'] = delivery_df.apply(resultofmatch,axis=1)

In [42]:
delivery_df[['batting_team', 'winner', 'result']].drop_duplicates().head(10)

                     batting_team                       winner  result
0           Kolkata Knight Riders        Kolkata Knight Riders       1
124   Royal Challengers Bangalore        Kolkata Knight Riders       0
225           Chennai Super Kings          Chennai Super Kings       1
349               Kings XI Punjab          Chennai Super Kings       0
473              Rajasthan Royals             Delhi Daredevils       0
595              Delhi Daredevils             Delhi Daredevils       1
692                Mumbai Indians  Royal Challengers Bangalore       0
815   Royal Challengers Bangalore  Royal Challengers Bangalore       1
938               Deccan Chargers        Kolkata Knight Riders       0
1178              Kings XI Punjab             Rajasthan Royals       0

In [43]:
final_df = delivery_df[['batting_team','bowling_team','city','runs_left',
                        'balls_left','wickets','total_runs_x','cur_run_rate',
                        'req_run_rate','result']]
                        
                        ##we are taking only important columns 

final_df.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,cur_run_rate,req_run_rate,result
0,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222,119,10,223,6.0,11.193277,1
1,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222,118,10,223,3.0,11.288136,1
2,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,117,10,223,4.0,11.333333,1
3,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,116,10,223,3.0,11.431034,1
4,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,115,10,223,2.4,11.530435,1

In [44]:
final_df.shape

(197397, 10)

In [45]:
final_df.isnull().sum()

batting_team        0
bowling_team        0
city            12397
runs_left           0
balls_left          0
wickets_left        0
total_runs_x        0
cur_run_rate        0
req_run_rate        0
result              0
dtype: int64

In [46]:
# dropping of null values

final_df = final_df.dropna()

final_df.isnull().sum()

batting_team    0
bowling_team    0
city            0
runs_left       0
balls_left      0
wickets_left    0
total_runs_x    0
cur_run_rate    0
req_run_rate    0
result          0
dtype: int64

In [47]:
final_df = final_df[final_df['balls_left'] != 0]

In [48]:
data = final_df.copy()

test = data['result']

train = data.drop(['result'],axis = 1)

train.head()

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,cur_run_rate,req_run_rate
0,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222,119,10,223,6.0,11.193277
1,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,222,118,10,223,3.0,11.288136
2,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,117,10,223,4.0,11.333333
3,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,116,10,223,3.0,11.431034
4,Kolkata Knight Riders,Royal Challengers Bangalore,Bangalore,221,115,10,223,2.4,11.530435

In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(train,test,test_size=0.2,random_state=1)

X_train.shape,X_test.shape

((147180, 9), (36795, 9))

In [50]:
X_train.columns

Index(['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left',
       'wickets_left', 'total_runs_x', 'cur_run_rate', 'req_run_rate'],
      dtype='object')

In [108]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
cf = ColumnTransformer(
    transformers=[
        ('tnf1', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
    ],
    remainder='passthrough',
    force_int_remainder_cols=False  # future-proofing
)

In [110]:
# creating the pipeline

# lr = LogisticRegression(solver='liblinear')
pipe = Pipeline(steps=[
    ('step1', cf),
    ('step2',LogisticRegression(solver='liblinear'))
])

# fitting the training data

pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('tnf1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [112]:
y_pred = pipe.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred))

0.5969561081668705

In [114]:
pipe.predict_proba(X_test)[10]

array([0.46496047, 0.53503953])

In [116]:
# rf = RandomForestClassifier()
pipe2 = Pipeline(steps=[
    ('step1', cf),
    ('step2',RandomForestClassifier())
])

pipe2.fit(X_train,y_train)
print(metrics.accuracy_score(y_test,pipe2.predict(X_test)))

0.9982878108438646

In [120]:
pipe2.predict_proba(X_test)[10]

array([1., 0.])

In [122]:
y_test.value_counts(normalize=True)

result
0    0.510939
1    0.489061
Name: proportion, dtype: float64

In [124]:
# saving the logistic regression model
import pickle
pickle.dump(pipe, open('pipe.pkl', 'wb'))